## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME'])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Determine the number of unique values in each column.
unique_values = application_df.nunique()
print(unique_values)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
app_type_counts = application_df['APPLICATION_TYPE'].value_counts()
print(app_type_counts)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
# Define the cutoff value for rare application types
cutoff_value = 500

# Create a list of application types to be replaced
application_types_to_replace = app_type_counts[app_type_counts < cutoff_value].index.tolist()

# Replace in DataFrame
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, "Other")

# Check to make sure replacement was successful
print(application_df['APPLICATION_TYPE'].value_counts())

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts_gt1 = classification_counts[classification_counts > 1]
print(classification_counts_gt1)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
# Look at value counts for CLASSIFICATION
classification_counts = application_df['CLASSIFICATION'].value_counts()

# Define a cutoff value for rare classifications
cutoff_value = 100  # Adjust this value as needed

# Create a list of classifications to replace
classifications_to_replace = classification_counts[classification_counts < cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
# Identify categorical columns
categorical_columns = application_df.select_dtypes(include=['object']).columns
print(categorical_columns)

Index(['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE',
       'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS'],
      dtype='object')

In [ ]:

# Convert categorical data to numeric using pd.get_dummies
application_df = pd.get_dummies(application_df, columns=categorical_columns, drop_first=True)

In [ ]:
print(application_df.head())

   STATUS  ASK_AMT  IS_SUCCESSFUL  APPLICATION_TYPE_T10  APPLICATION_TYPE_T19  \
0       1     5000              1                  True                 False
1       1   108590              1                 False                 False
2       1     5000              0                 False                 False
3       1     6692              1                 False                 False
4       1   142590              1                 False                 False

   APPLICATION_TYPE_T3  APPLICATION_TYPE_T4  APPLICATION_TYPE_T5  \
0                False                False                False
1                 True                False                False
2                False                False                 True
3                 True                False                False
4                 True                False                False

   APPLICATION_TYPE_T6  APPLICATION_TYPE_T7  ...  ORGANIZATION_Trust  \
0                False                False  ...               False
1                False                False  ...               False
2                False                False  ...               False
3                False                False  ...                True
4                False                False  ...                True

   INCOME_AMT_1-9999  INCOME_AMT_10000-24999  INCOME_AMT_100000-499999  \
0              False                   False                     False
1               True                   False                     False
2              False                   False                     False
3              False                    True                     False
4              False                   False                      True

   INCOME_AMT_10M-50M  INCOME_AMT_1M-5M  INCOME_AMT_25000-99999  \
0               False             False                   False
1               False             False                   False
2               False             False                   False
3               False             False                   False
4               False             False                   False

   INCOME_AMT_50M+  INCOME_AMT_5M-10M  SPECIAL_CONSIDERATIONS_Y
0            False              False                     False
1            False              False                     False
2            False              False                     False
3            False              False                     False
4            False              False                     False

[5 rows x 43 columns]

In [ ]:
# Split our preprocessed data into our features and target arrays
# Separate the target column and feature columns
X = application_df.drop(columns=['IS_SUCCESSFUL'])  # Features
y = application_df['IS_SUCCESSFUL']  # Target

# Split the preprocessed data into a training and testing dataset
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.


nn = tf.keras.models.Sequential()

# First hidden layer
# Let's assume we have 10 features after scaling and decide to start with 128 nodes
nn.add(tf.keras.layers.Dense(units=128, activation='relu', input_dim=X_train_scaled.shape[1]))

# Second hidden layer
# You can experiment with 64 nodes
nn.add(tf.keras.layers.Dense(units=64, activation='relu'))

# Output layer
# For binary classification, use 1 output unit with sigmoid activation
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 128)                 │           5,504 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              65 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 13,825 (54.00 KB)

 Trainable params: 13,825 (54.00 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Compile the model
nn.compile(optimizer='adam',               # Adam optimizer is widely used
           loss='binary_crossentropy',      # Binary crossentropy for binary classification
           metrics=['accuracy'])           # Accuracy as the evaluation metric

In [ ]:
# Train the model
history = nn.fit(X_train_scaled, y_train,
                 epochs=50,        # Number of training iterations (adjust as needed)
                 batch_size=32,     # Number of samples per gradient update (adjust as needed)
                 validation_data=(X_test_scaled, y_test),  # Use validation data for evaluation
                 verbose=2)         # Set verbose to 2 to print the progress bar and loss/accuracy at each epoch

Epoch 1/50
858/858 - 5s - 6ms/step - accuracy: 0.7215 - loss: 0.5698 - val_accuracy: 0.7258 - val_loss: 0.5601
Epoch 2/50
858/858 - 2s - 2ms/step - accuracy: 0.7298 - loss: 0.5539 - val_accuracy: 0.7229 - val_loss: 0.5594
Epoch 3/50
858/858 - 2s - 2ms/step - accuracy: 0.7303 - loss: 0.5506 - val_accuracy: 0.7207 - val_loss: 0.5582
Epoch 4/50
858/858 - 2s - 3ms/step - accuracy: 0.7304 - loss: 0.5490 - val_accuracy: 0.7217 - val_loss: 0.5574
Epoch 5/50
858/858 - 2s - 2ms/step - accuracy: 0.7326 - loss: 0.5473 - val_accuracy: 0.7296 - val_loss: 0.5535
Epoch 6/50
858/858 - 3s - 3ms/step - accuracy: 0.7315 - loss: 0.5461 - val_accuracy: 0.7251 - val_loss: 0.5550
Epoch 7/50
858/858 - 2s - 2ms/step - accuracy: 0.7352 - loss: 0.5447 - val_accuracy: 0.7270 - val_loss: 0.5559
Epoch 8/50
858/858 - 2s - 3ms/step - accuracy: 0.7328 - loss: 0.5449 - val_accuracy: 0.7294 - val_loss: 0.5524
Epoch 9/50
858/858 - 3s - 3ms/step - accuracy: 0.7338 - loss: 0.5437 - val_accuracy: 0.7293 - val_loss: 0.5519
Epoch 10/50
858/858 - 2s - 2ms/step - accuracy: 0.7346 - loss: 0.5431 - val_accuracy: 0.7306 - val_loss: 0.5525
Epoch 11/50
858/858 - 4s - 5ms/step - accuracy: 0.7343 - loss: 0.5426 - val_accuracy: 0.7239 - val_loss: 0.5543
Epoch 12/50
858/858 - 4s - 4ms/step - accuracy: 0.7346 - loss: 0.5426 - val_accuracy: 0.7287 - val_loss: 0.5526
Epoch 13/50
858/858 - 3s - 3ms/step - accuracy: 0.7344 - loss: 0.5424 - val_accuracy: 0.7257 - val_loss: 0.5557
Epoch 14/50
858/858 - 2s - 2ms/step - accuracy: 0.7353 - loss: 0.5416 - val_accuracy: 0.7302 - val_loss: 0.5528
Epoch 15/50
858/858 - 2s - 2ms/step - accuracy: 0.7356 - loss: 0.5415 - val_accuracy: 0.7302 - val_loss: 0.5514
Epoch 16/50
858/858 - 3s - 3ms/step - accuracy: 0.7371 - loss: 0.5408 - val_accuracy: 0.7257 - val_loss: 0.5532
Epoch 17/50
858/858 - 4s - 5ms/step - accuracy: 0.7357 - loss: 0.5408 - val_accuracy: 0.7310 - val_loss: 0.5560
Epoch 18/50
858/858 - 3s - 3ms/step - accuracy: 0.7372 - loss: 0.5405 - val_accuracy: 0.7289 - val_loss: 0.5521
Epoch 19/50
858/858 - 3s - 3ms/step - accuracy: 0.7360 - loss: 0.5402 - val_accuracy: 0.7286 - val_loss: 0.5557
Epoch 20/50
858/858 - 3s - 4ms/step - accuracy: 0.7369 - loss: 0.5396 - val_accuracy: 0.7305 - val_loss: 0.5519
Epoch 21/50
858/858 - 4s - 5ms/step - accuracy: 0.7368 - loss: 0.5395 - val_accuracy: 0.7303 - val_loss: 0.5526
Epoch 22/50
858/858 - 2s - 3ms/step - accuracy: 0.7373 - loss: 0.5392 - val_accuracy: 0.7280 - val_loss: 0.5524
Epoch 23/50
858/858 - 3s - 3ms/step - accuracy: 0.7376 - loss: 0.5393 - val_accuracy: 0.7290 - val_loss: 0.5531
Epoch 24/50
858/858 - 3s - 4ms/step - accuracy: 0.7377 - loss: 0.5388 - val_accuracy: 0.7268 - val_loss: 0.5572
Epoch 25/50
858/858 - 2s - 2ms/step - accuracy: 0.7376 - loss: 0.5387 - val_accuracy: 0.7306 - val_loss: 0.5519
Epoch 26/50
858/858 - 2s - 3ms/step - accuracy: 0.7378 - loss: 0.5382 - val_accuracy: 0.7302 - val_loss: 0.5538
Epoch 27/50
858/858 - 2s - 2ms/step - accuracy: 0.7376 - loss: 0.5379 - val_accuracy: 0.7248 - val_loss: 0.5532
Epoch 28/50
858/858 - 3s - 3ms/step - accuracy: 0.7372 - loss: 0.5380 - val_accuracy: 0.7313 - val_loss: 0.5539
Epoch 29/50
858/858 - 2s - 2ms/step - accuracy: 0.7377 - loss: 0.5377 - val_accuracy: 0.7300 - val_loss: 0.5551
Epoch 30/50
858/858 - 3s - 4ms/step - accuracy: 0.7375 - loss: 0.5376 - val_accuracy: 0.7303 - val_loss: 0.5541
Epoch 31/50
858/858 - 2s - 2ms/step - accuracy: 0.7380 - loss: 0.5374 - val_accuracy: 0.7276 - val_loss: 0.5548
Epoch 32/50
858/858 - 2s - 2ms/step - accuracy: 0.7381 - loss: 0.5370 - val_accuracy: 0.7292 - val_loss: 0.5519
Epoch 33/50
858/858 - 3s - 3ms/step - accuracy: 0.7381 - loss: 0.5366 - val_accuracy: 0.7294 - val_loss: 0.5534
Epoch 34/50
858/858 - 2s - 2ms/step - accuracy: 0.7377 - loss: 0.5367 - val_accuracy: 0.7284 - val_loss: 0.5558
Epoch 35/50
858/858 - 2s - 2ms/step - accuracy: 0.7383 - loss: 0.5369 - val_accuracy: 0.7302 - val_loss: 0.5549
Epoch 36/50
858/858 - 3s - 4ms/step - accuracy: 0.7382 - loss: 0.5364 - val_accuracy: 0.7303 - val_loss: 0.5548
Epoch 37/50
858/858 - 2s - 2ms/step - accuracy: 0.7381 - loss: 0.5366 - val_accuracy: 0.7318 - val_loss: 0.5536
Epoch 38/50
858/858 - 2s - 3ms/step - accuracy: 0.7377 - loss: 0.5361 - val_accuracy: 0.7297 - val_loss: 0.5544
Epoch 39/50
858/858 - 3s - 3ms/step - accuracy: 0.7388 - loss: 0.5354 - val_accuracy: 0.7309 - val_loss: 0.5557
Epoch 40/50
858/858 - 2s - 2ms/step - accuracy: 0.7395 - loss: 0.5358 - val_accuracy: 0.7303 - val_loss: 0.5530
Epoch 41/50
858/858 - 3s - 3ms/step - accuracy: 0.7388 - loss: 0.5353 - val_accuracy: 0.7281 - val_loss: 0.5581
Epoch 42/50
858/858 - 3s - 3ms/step - accuracy: 0.7390 - loss: 0.5356 - val_accuracy: 0.7312 - val_loss: 0.5535
Epoch 43/50
858/858 - 4s - 5ms/step - accuracy: 0.7391 - loss: 0.5348 - val_accuracy: 0.7294 - val_loss: 0.5571
Epoch 44/50
858/858 - 2s - 3ms/step - accuracy: 0.7399 - loss: 0.5352 - val_accuracy: 0.7274 - val_loss: 0.5588
Epoch 45/50
858/858 - 2s - 3ms/step - accuracy: 0.7393 - loss: 0.5348 - val_accuracy: 0.7313 - val_loss: 0.5557
Epoch 46/50
858/858 - 2s - 2ms/step - accuracy: 0.7397 - loss: 0.5344 - val_accuracy: 0.7292 - val_loss: 0.5580
Epoch 47/50
858/858 - 3s - 3ms/step - accuracy: 0.7395 - loss: 0.5351 - val_accuracy: 0.7270 - val_loss: 0.5575
Epoch 48/50
858/858 - 2s - 2ms/step - accuracy: 0.7392 - loss: 0.5342 - val_accuracy: 0.7255 - val_loss: 0.5587
Epoch 49/50
858/858 - 3s - 3ms/step - accuracy: 0.7392 - loss: 0.5342 - val_accuracy: 0.7292 - val_loss: 0.5579
Epoch 50/50
858/858 - 3s - 3ms/step - accuracy: 0.7397 - loss: 0.5343 - val_accuracy: 0.7271 - val_loss: 0.5581

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - 2ms/step - accuracy: 0.7271 - loss: 0.5581
Loss: 0.5580977201461792, Accuracy: 0.7271137237548828

In [ ]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.